export const FETCH_USER = 'fetch_user'
export const FETCH_SURVEYS = 'fetch_surveys'
export const SET_SEARCH = 'set_search'
export const SET_IS_FETCHING_SURVEYS = 'is_fetching_surveys'
export const SET_INITIAL_FETCHING_SURVEYS = 'set_initial_fetching_surveys'
